#! /bin/bash

if [ "$1" == "" ]; then
  echo "Expected hostname:port of server to load test. For example:"
  echo "  test/load firepick"
  exit -1
fi
if [ ! -e target ]; then
  mkdir target
fi

function test() {
  echo $1 |& tee -a target/load.log
  siege -r 100 -b -c 1 $1 |& tee -a target/load.log
}

echo "RUNNING LOAD TEST" > target/load.log
date >> target/load.log
test http://$1/firerest/cv/1/gray/cve/calc-offset/save.fire 
test http://$1/firerest/cv/1/gray/cve/calc-offset/process.fire 
test http://$1/firerest/cv/1/camera.jpg 
test http://$1/firerest/cv/1/monitor.jpg 
test http://$1/firerest/cv/1/output.jpg 
test http://$1/firerest/cv/1/bgr/cve/calc-offset/save.fire 
test http://$1/firerest/cv/1/bgr/cve/calc-offset/process.fire 
