#! /bin/bash

FIREREST_VERSION_MAJOR=0
FIREREST_VERSION_MINOR=6
FIREREST_VERSION_PATCH=0

echo "VERSION  : $FIREREST_VERSION_MAJOR.$FIREREST_VERSION_MINOR.$FIREREST_VERSION_PATCH"
echo "CONFIG   : `grep version www/firerest/config.json`"
echo "PATH     : $PATH"
echo "SHELL    : $SHELL"
echo "SUDO_USER: $SUDO_USER"

ps -eo uid,args | grep -E firerest.js | grep node > /dev/null
if [ $? -eq 0 ]; then
  echo "----------------------------------------"
  echo "ERROR    : FireREST is already running"
  echo "SOLUTION : Kill the existing FireREST process before proceeding with the build:"
  echo "PID      : `ps -e -o pid,command | grep -E "firerest.js" | grep -v grep`"
  exit -1
fi

if [ "$(type -p lsb_release)" == "" ]; then
  echo "++++++++++++++++++ INSTALLING lsb_release ++++++++++++"
  apt-get install -y lsb-release
fi
if [ "$(arch)" != "armv6l" ] || [ "$(lsb_release -is)" != "Debian" ] ;then
  RASPBIAN=0
else
  RASPBIAN=1
fi

if [ "$SUDO_USER" == "" ]; then
  echo "SUDO_USER is not defined. You must run this script as superuser:"
  echo '  sudo ./build'
  exit -1
fi

sudo -u $SUDO_USER sed \
  -e s/@@FIREREST_VERSION_MAJOR@@/$FIREREST_VERSION_MAJOR/ \
  -e s/@@FIREREST_VERSION_MINOR@@/$FIREREST_VERSION_MINOR/ \
  -e s/@@FIREREST_VERSION_PATCH@@/$FIREREST_VERSION_PATCH/ \
  config.json > www/firerest/config.json

if [ "$(type -p siege)" == "" ]; then
  echo "++++++++++++++++++ INSTALLING siege ++++++++++++"
  apt-get install -y siege
else 
  echo "COMPONENT: siege installed"
fi

if [ "$(type -p node)" == "" ]; then
  echo "++++++++++++++++++ INSTALLING NodeJS ++++++++++++"
  if [ $RASPBIAN -eq 1 ]; then
    mkdir /opt/node
    pushd /opt/node
    wget http://nodejs.org/dist/v0.10.22/node-v0.10.22-linux-arm-pi.tar.gz
    tar xvzf node-*-linux-arm-pi.tar.gz
    rm node-*-linux-arm-pi.tar.gz
    cd /usr/local/bin
    ln -s /opt/node/node-*pi/bin/node node
    ln -s /opt/node/node-*pi/bin/npm npm
    popd
  else
   echo PLEASE INSTALL nodeJS
   exit -1
  fi
else
  echo "COMPONENT: NodeJS installed"
fi
#if [ "$(type -p npm)" == "" ]; then
#  echo "You must provide this environment's PATH:"
#  echo '  sudo PATH=$PATH ./build'
#  exit -1
#fi
if [ ! -e node_modules ]; then
  echo "++++++++++++++++++ INSTALLING NodeJS dependencies ++++++++++++"
  npm install
else
  echo "COMPONENT: node_modules installed"
fi

function build_git() {
  echo "++++++++++++++++++ BUILDING $1 ++++++++++++"
  if [ ! -e $1 ]; then
    sudo -u $SUDO_USER git clone git://github.com/firepick1/$1
  fi
  pushd $1
  sudo -u $SUDO_USER git pull
  ./build
  if [ $? -ne 0 ]; then
    echo "COMPONENT: $1 INSTALLATION FAILED"
    exit -1
  fi
  popd
}

if [ $RASPBIAN -ne 1 ]; then
  echo "PROVIDER : FireREST reference implementation. Static content only"
  echo "STATUS   : Build complete"
else 
  echo "PROVIDER : Raspberry Pi FireFUSE with live content"
  if [ -e version-$FIREREST_VERSION_MAJOR.$FIREREST_VERSION_MINOR ] && [ -e /dev/firefuse/status ] ; then
    echo "COMPONENT: FireREST dependencies OK"
  else
    build_git FireSight
    build_git FireFUSE
  fi
fi

date > version-$FIREREST_VERSION_MAJOR.$FIREREST_VERSION_MINOR

echo "STATUS   : FireREST build complete."
echo "------------------------------------------"
echo "Launch FireREST web service:"
echo "  node server/firesight.js"
echo "Verify FireREST web service at http://localhost:8080"
