#! /bin/bash

echo
echo "COMMAND	: $0 $@ # FireREST/FireFUSE visual calibration utility"

function help() {
  echo "SYNOPSIS: fire/calibrate [-h]"
  echo "EXAMPLE	: Generate position offsets"
  echo "	:   fire/calibrate -o"
  echo "EXAMPLE	: Print this documentation:"
  echo "	:   fire/calibrate -h"
}

if [ "$1" == "" ] || [ "$1" == "-h" ]; then help; exit 0; fi

IMAGES=/var/firefuse/calibration
GCODEFIRE=/dev/firefuse/cnc/marlin/gcode.fire
if [ ! -e $GCODEFIRE ]; then
  echo "ERROR	: FireFUSE serial connection to Marlin is unavailable"
  echo "TRY	: See /var/log/firefuse.log for details"
  exit -1
fi

function gcode() {
  if [ "$2" != "" ]; then echo "STATUS	: $2"; fi
  echo "GCODE	: $1"
  echo "$1" > $GCODEFIRE
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
  sleep 5
  return $RC
}

function imageAt() {
  echo "IMAGE	: $1"
  gcode G0$1M400
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: echo $GCODE > $GCODEFIRE => $RC"; exit -1; fi
  cp /dev/firefuse/sync/cv/1/camera.jpg $IMAGES/$1.jpg
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
}

function calcoffset() {
  firesight -ji 0 -p FireSight/json/calcOffset.json -Dtemplate=$IMAGES/$1 -i $IMAGES/$2 
}

function calcoffsetAt() {
  imageAt $1
  firesight -ji 0 -p FireSight/json/calcOffset.json -Dtemplate=$IMAGES/$2.jpg -i $IMAGES/$1.jpg 
}

if [ "$1" == "-o" ]; then
  gcode G28Z0 "Homing"

  imageAt X0Y0Z0
  calcoffsetAt X1Y1Z0 X0Y0Z0
  calcoffsetAt X-1Y1Z0 X0Y0Z0
  calcoffsetAt X1Y-1Z0 X0Y0Z0
  calcoffsetAt X-1Y-1Z0 X0Y0Z0

  imageAt X0Y0Z-1
  calcoffsetAt X1Y1Z-1 X0Y0Z-1
  calcoffsetAt X-1Y1Z-1 X0Y0Z-1
  calcoffsetAt X1Y-1Z-1 X0Y0Z-1
  calcoffsetAt X-1Y-1Z-1 X0Y0Z-1

  imageAt X0Y0Z-2
  calcoffsetAt X1Y1Z-2 X0Y0Z-2
  calcoffsetAt X-1Y1Z-2 X0Y0Z-2
  calcoffsetAt X1Y-1Z-2 X0Y0Z-2
  calcoffsetAt X-1Y-1Z-2 X0Y0Z-2

  echo "SUCCESS	: calibrated"
  exit 0;
fi
