#! /bin/bash

echo
echo "COMMAND	: $0 $@ # FireREST/FireFUSE visual calibration utility"

function help() {
  echo "SYNOPSIS: fire/calibrate [-h]"
  echo "EXAMPLE	: Generate position offsets"
  echo "	:   fire/calibrate -o"
  echo "EXAMPLE	: Print this documentation:"
  echo "	:   fire/calibrate -h"
}

if [ "$1" == "" ] || [ "$1" == "-h" ]; then help; exit 0; fi

IMAGES=/var/firefuse/calibration
GCODEFIRE=/dev/firefuse/cnc/marlin/gcode.fire
if [ ! -e $GCODEFIRE ]; then
  echo "ERROR	: FireFUSE serial connection to Marlin is unavailable"
  echo "TRY	: See /var/log/firefuse.log for details"
  exit -1
fi

function gcode() {
  if [ "$2" != "" ]; then echo "STATUS	: $2"; fi
  echo "GCODE	: $1"
  echo "$1" > $GCODEFIRE
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
}

function imageAt() {
  echo "IMAGE	: $1"
  GCODE=G0$1M400
  echo $GCODE > $GCODEFIRE
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: echo $GCODE > $GCODEFIRE => $RC"; exit -1; fi
  cp /dev/firefuse/sync/cv/1/camera.jpg $IMAGES/$1.jpg
  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
}

function calcoffset() {
  firesight -p FireSight/json/calcOffset.json -Dtemplate=$IMAGES/$1 -i $IMAGES/$1
}

if [ "$1" == "-o" ]; then
  gcode G28Z0 "Homing"
  imageAt X0Y0Z0
  imageAt X1Y1Z0
  calcoffset X0Y0Z0.jpg X1Y1Z0.jpg

  echo "STATUS	: changed default configuration file"
  echo "SUCCESS	: "`ls -l config-default.json | grep -o config.*json`
  exit 0;
fi
