#! /bin/bash

echo
echo "COMMAND	: $0 $@ # FireREST/FireFUSE visual calibration utility"

if [ ! -L "config-default.json" ]; then 
  echo "STATUS	: setting default to www/config.json"
  ln -sTf www/config.json config-default.json; 
fi
echo "DEFAULT	: "`ls -l config-default.json | grep -o config.*json`

function help() {
  echo "SYNOPSIS: fire/calibrate [-h]"
  echo "EXAMPLE	: Generate position offsets
  echo "	:   fire/calibrate -o
  echo "EXAMPLE	: Print this documentation:"
  echo "	:   fire/calibrate -h"
  echo "SEE ALSO: https://github.com/firepick1/FireREST/wiki/config.json"
}

if [ "$1" == "" ] || [ "$1" == "-h" ]; then help; exit 0; fi

if [ ! -e /dev/firefuse/cnc/marlin/gcode.ff ]; then
  echo "ERROR	: FireFUSE serial connection to Marlin is unavailable"
  echo "TRY		: Look at /var/log/firefuse.log for details"
  exit -1
fi

if [ "$1" == "-o" ]; then
  echo "STATUS	: changed default configuration file"
  echo "SUCCESS	: "`ls -l config-default.json | grep -o config.*json`
  exit 0;
fi
