#! /bin/bash

echo
echo "COMMAND	: fire/config $@ # FireREST/FireFUSE configuration utility"

if [ ! -L "config/default.json" ]; then 
  echo "CONFIG	: setting default to www/config.json"
  ln -sTf www/config.json config/default.json; 
fi
echo "DEFAULT	: "`ls -l config/default.json | grep -o config.*json`

function help() {
  echo "SYNOPSIS: fire/config [-d]"
  echo "	: fire/config "`tput smul`"config.json"`tput rmul`
  echo "	: fire/config -e "`tput smul`"edit.json"`tput rmul`
  echo "	: fire/config -D "`tput smul`"default.json"`tput rmul`
  echo "EXAMPLES: Apply default configuration file:"
  echo "	:   fire/config -d"
  echo "EXAMPLES: Set default configuration file:"
  echo "	:   fire/config -D myconfig.json"
  echo "EXAMPLES: Edit current configuration file to use 400x400 camera:"
  echo "	:   fire/config -e examples/400x400.json"
  echo "EXAMPLES: Apply custom configuration file:"
  echo "	:   fire/config custom/myconfig.json"
  echo "	: Print this documentation:"
  echo "	:   fire/config -h"
  echo "SEE ALSO: https://github.com/firepick1/FireREST/wiki/config.json"
}

if [ "$1" == "" ] || [ "$1" == "-h" ]; then help; exit 0; fi
if [ "$1" == "-e" ]; then EDIT=1; shift; else EDIT=0; fi
if [ "$1" == "-D" ]; then
  if [ "$2" == "" ]; then
    ln -sfT www/config.json config/default.json
  elif [ -e "$2" ]; then 
    ln -sfT "$2" config/default.json
  else 
    echo "ERROR	: $2 not found"
    exit -1
  fi
  echo "STATUS	: changed default configuration file"
  echo "SUCCESS	: "`ls -l config/default.json | grep -o config.*json`
  exit 0;
fi

CONFIG_FILE=$1
if [ "$1" == "-d" || "$1" == "DEFAULT" ]; then CONFIG_FILE=config/default.json; fi
if [ ! -e "$CONFIG_FILE" ]; then
  echo "ERROR	: $CONFIG_FILE not found"
  exit -1;
fi
echo "CONFIG	: "`ls -l $CONFIG_FILE | grep -o config.*json`

sudo -k
ls /dev | grep firefuse > /dev/null
if [ $? -ne 0 ]; then
  echo "ERROR	: FireFUSE is not installed and cannot be configured" 
  exit -1;
fi

ls /dev/firefuse > /dev/null
if [ $? -ne 0 ]; then
  echo "WARNING	: FireFUSE may have crashed. Attempting to unmount /dev/firefuse..." 
  sudo fusermount -u /dev/firefuse
  if [ $? -ne 0 ]; then
    echo "ERROR	: /dev/firefuse could not be unmounted"
    exit -1
  fi
fi

if [ -e /dev/firefuse/status ]; then
  echo "FireFUSE: Unmounting running instance: /dev/firefuse..."
  sudo fusermount -u /dev/firefuse
  if [ $? -ne 0 ]; then
    echo "ERROR	: /dev/firefuse could not be unmounted"
    exit -1
  fi
else 
  echo "FireFUSE: No existing instance detected at /dev/firefuse"
fi

if [ $EDIT -ne 0 ]; then
  echo "CONFIG	: /var/firefuse/config.json + $CONFIG_FILE"
  grunt cfg-custom:/var/firefuse/config.json:$CONFIG_FILE
else
  echo "CONFIG	: $CONFIG_FILE"
  sudo cp $CONFIG_FILE /var/firefuse/config.json
fi
if [ $? -ne 0 ]; then
  echo "ERROR	: could not update /var/firefuse/config.json"
  exit -1
fi
pushd ~/FireREST/FireFUSE > /dev/null
  sudo target/firefuse -o allow_other /dev/firefuse
  if [ $? -ne 0 ]; then
    echo "ERROR	: /dev/firefuse could not be restarted"
    exit -1
  fi
popd > /dev/null
echo "SUCCESS	: Configuration installed"
echo "LOG	: To monitor FireFUSE activity, see /var/log/firefuse.log"
echo "------------------------------"
echo 
tail /var/log/firefuse.log
