#! /bin/bash

function help() {
  echo "NAME"
  echo "	fire/config - Update FireREST/FireFUSE configuration"
  echo""
  echo "SYNOPSIS"
  echo "	fire/config [-d]"
  echo "	fire/config "`tput smul`"config.json"`tput rmul`
  echo ""
  echo "EXAMPLES"
  echo "	Apply default configuration file:"
  echo "	  fire/config -d"
  echo 
  echo "	Apply custom configuration file:"
  echo "	  fire/config custom/myconfig.json"
  echo 
  echo "	Print this documentation:"
  echo "	   fire/config -h"
  echo
  echo "SEE ALSO"
  echo "	https://github.com/firepick1/FireREST/wiki/config.json"
}

if [ "$1" == "" ] || [ "$1" == "-h" ]; then help; exit 0; fi

CONFIG_FILE=$1
if [ "$1" == "-d" ]; then CONFIG_FILE=www/config.json; fi
if [ "$1" == "DEFAULT" ]; then CONFIG_FILE=www/config.json; fi
if [ ! -e "$CONFIG_FILE" ]; then
  echo "ERROR	: $CONFIG_FILE not found"
  exit -1;
fi

sudo -k
ls /dev | grep firefuse > /dev/null
if [ $? -ne 0 ]; then
  echo "ERROR	: FireFUSE is not installed and cannot be configured" 
  exit -1;
fi

ls /dev/firefuse > /dev/null
if [ $? -ne 0 ]; then
  echo "WARNING	: FireFUSE may have crashed. Attempting to unmount /dev/firefuse..." 
  sudo fusermount -u /dev/firefuse
  if [ $? -ne 0 ]; then
    echo "ERROR	: /dev/firefuse could not be unmounted"
    exit -1
  fi
fi

if [ -e /dev/firefuse/status ]; then
  echo "FireFUSE: Unmounting running instance: /dev/firefuse..."
  sudo fusermount -u /dev/firefuse
  if [ $? -ne 0 ]; then
    echo "ERROR	: /dev/firefuse could not be unmounted"
    exit -1
  fi
else 
  echo "FireFUSE: No existing instance detected at /dev/firefuse"
fi

echo "CONFIG	: $CONFIG_FILE"
sudo cp $CONFIG_FILE /var/firefuse/config.json
if [ $? -ne 0 ]; then
  echo "ERROR	: could not copy configuration $CONFIG_FILE to /var/firefuse/config.json"
  exit -1
fi
pushd ~/FireREST/FireFUSE > /dev/null
  sudo target/firefuse -o allow_other /dev/firefuse
  if [ $? -ne 0 ]; then
    echo "ERROR	: /dev/firefuse could not be restarted"
    exit -1
  fi
popd > /dev/null
echo "SUCCESS	: Configuration installed"
echo "LOG	: To monitor FireFUSE activity, see /var/log/firefuse.log"
echo "------------------------------"
echo 
tail /var/log/firefuse.log
