#! /bin/bash

function help() {
  echo "NAME"
  echo "	fire/log - FireFUSE log utility"
  echo""
  echo "SYNOPSIS"
  echo "	fire/log [-c|-t|-d|-i|-h]"
  echo ""
  echo "EXAMPLES"
  echo "	Show recent entries"
  echo "	  fire/log"
  echo 
  echo "	Continuously copy log entries to console (CTRL-C to quit)"
  echo "	  fire/log -c"
  echo 
  echo "	Log at TRACE level and show fully detailed information about FireFUSE activity"
  echo "	  fire/log -t"
  echo 
  echo "	Log at DEBUG level and show some detailed information about FireFUSE activity"
  echo "	  fire/log -d"
  echo 
  echo "	Log at INFO level (default):"
  echo "	  fire/log -i"
  echo 
  echo "	Print this documentation:"
  echo "	   fire/log -h"
}

if [ "$1" == "-h" ]; then help; exit 0; fi

sudo -k
ls /dev | grep firefuse
if [ $? -ne 0 ]; then
  echo "ERROR	: FireFUSE is not installed" 
  exit -1;
fi

ls /dev/firefuse | grep status
if [ $? -ne 0 ]; then
  echo "ERROR	: FireFUSE may have crashed." 
  echo "TRY	: fire/config -d" 
  exit -1
fi

if [ "$1" == "-c" ]; then
  echo "LOG	: Copy log entries to stdout. CTRL-C to quit."
  tail -f /var/log/firefuse.log
  exit 0
fi 

if [ "$1" == "-t" ]; then
  echo "LOG	: Logging set to TRACE level. See /var/log/firefuse.log"
  echo t > /dev/firefuse/firefuse.log
fi 

if [ "$1" == "-d" ]; then
  echo "LOG	: Logging set to DEBUG level. See /var/log/firefuse.log"
  echo d > /dev/firefuse/firefuse.log
fi

if [ "$1" == "-i" ]; then
  echo "LOG	: Logging set to INFO level. See /var/log/firefuse.log"
  echo i > /dev/firefuse/firefuse.log
fi

echo "--------------------------------"
tail /var/log/firefuse.log
