#! /bin/bash

echo "COMMAND	: fire/log shows latest FireFUSE log emtries"
echo "HELP	: fire/log -h	"

function help() {
  echo "SYNOPSIS: fire/log [-c|-t|-d|-i|-h]"
  echo "EXAMPLES: Show recent entries"
  echo "	:   fire/log"
  echo "	: Continuously copy log entries to console (CTRL-C to quit)"
  echo "	:   fire/log -c"
  echo "	: Log at TRACE level and show fully detailed information about FireFUSE activity"
  echo "	:   fire/log -t"
  echo "	: Log at DEBUG level and show some detailed information about FireFUSE activity"
  echo "	:   fire/log -d"
  echo "	: Log at INFO level (default):"
  echo "	:   fire/log -i"
  echo "	: Print this documentation:"
  echo "	:   fire/log -h"
}

if [ "$1" == "-h" ]; then help; exit 0; fi

sudo -k
ls /dev | grep firefuse > /dev/null
if [ $? -ne 0 ]; then
  echo "ERROR	: FireFUSE is not installed" 
  exit -1;
fi

ls /dev/firefuse | grep status > /dev/null
if [ $? -ne 0 ]; then
  echo "ERROR	: FireFUSE may have crashed." 
  echo "TRY	: fire/config -d" 
  exit -1
fi

if [ "$1" == "-c" ]; then
  echo "LOG	: Copy log entries to stdout. CTRL-C to quit."
  tail -f /var/log/firefuse.log
  exit 0
fi 

if [ "$1" == "-t" ]; then
  echo "LOG	: Logging set to TRACE level. See /var/log/firefuse.log"
  echo t > /dev/firefuse/firelog
fi 

if [ "$1" == "-d" ]; then
  echo "LOG	: Logging set to DEBUG level. See /var/log/firefuse.log"
  echo d > /dev/firefuse/firelog
fi

if [ "$1" == "-i" ]; then
  echo "LOG	: Logging set to INFO level. See /var/log/firefuse.log"
  echo i > /dev/firefuse/firelog
fi

echo "--------------------------------"
tail /var/log/firefuse.log
