#! /bin/bash

echo "COMMAND	: fire/udpate"

echo "GIT	: `git config remote.origin.url`"
git pull
if [ $? -ne 0 ]; then
  echo "ERROR	: Could not retrieve latest source from GitHub"
  exit -1;
fi

echo "SUDO	: require password for changing machine configuration"
sudo -k
sudo -E ./build &> build.log
if [ $? -ne 0 ]; then
  echo "ERROR	: Could not build FireREST"
  exit -1
fi
echo "SUCCESS	: FireREST updated and built"
