#! /bin/bash

echo "COMMAND	: fire/upgrade - Get and build latest version of FireREST"
echo "ETA	: 1-30 minutes"
echo "HELP	: https://github.com/firepick1/FireREST/wiki/Upgrade-FireREST"
echo "HELP	: fire/upgrade -a   # rebuild everything"

fire/web -k

echo "GIT	: `git config remote.origin.url`"
git pull
if [ $? -ne 0 ]; then
  echo "ERROR	: Could not retrieve latest source from GitHub"
  exit -1;
fi

if [ ! -e fire/upgrade ]; then
	echo "ERROR	: fire/upgrade must be run from the FireREST directory"
	exit -1
fi

fire/upgrade-main
