#! /bin/bash

echo "COMMAND	: fire/upgrade - Get and build latest version of FireREST"
echo "ETA	: 1-30 minutes"
echo "HELP	: https://github.com/firepick1/FireREST/wiki/Upgrade-FireREST"
echo "HELP	: fire/upgrade -a   # rebuild everything"

fire/web -k

echo "GIT	: `git config remote.origin.url`"
git pull
if [ $? -ne 0 ]; then
  echo "ERROR	: Could not retrieve latest source from GitHub"
  exit -1;
fi

echo "SUDO	: verifying sudo privilege for changing machine configuration"
sudo -K
sudo echo "SUDO	: confirmed"
if [ "$1" == "-a" ]; then
  echo "STATUS	: full buid requested (-a)"
  rm version-*
fi
echo "LOG	: `pwd`/build.log (started)"
./build |& tee build.log
if [ $? -ne 0 ]; then
  echo "----------------------------------"
  echo "ERROR	: Could not build FireREST"
  echo "ERROR	: See build.log"
  exit -1
fi
echo "LOG	: `pwd`/build.log"
echo "SUCCESS	: fire/upgrade - FireREST upgrade complete"

